# Generated by Django 5.0.6 on 2024-05-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
