# Generated by Django 5.0.6 on 2024-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
