# Generated by Django 5.0.6 on 2024-05-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_returnrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
