# Generated by Django 5.0.6 on 2024-06-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.PositiveIntegerField()),
                ('minimum', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bonus'),
        ),
    ]
