# Generated by Django 5.0.6 on 2024-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_bonus_product_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
