# Generated by Django 5.0.6 on 2024-06-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_bonus_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='bonus_amount',
            new_name='amount',
        ),
    ]
