# Generated by Django 5.0.6 on 2024-06-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_orderitem_rr_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
