# Generated by Django 5.0.6 on 2024-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_cartitem_type_remove_orderitem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Bonus', 'Bonus')], default='Regular', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Bonus', 'Bonus')], default='Regular', max_length=10),
        ),
    ]
