# Generated by Django 5.0.6 on 2024-06-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cartitem_type_orderitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bonus_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bonus_minimum',
            field=models.PositiveIntegerField(default=9999999),
        ),
    ]
