# Generated by Django 5.0.6 on 2024-06-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='author',
        ),
    ]
