# Generated by Django 5.0.6 on 2024-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_returnrequest_price_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
