# Generated by Django 5.0.6 on 2024-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_returnrequest_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='bonus_return',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
