# Generated by Django 5.0.6 on 2024-06-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_returnrequest_bonus_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='bonus_return',
            field=models.PositiveIntegerField(),
        ),
    ]
